---
- name: Check Ubuntu version
  ansible.builtin.assert:
    that:
      - ansible_distribution == "Ubuntu"
      - ansible_distribution_version is version("20.04", "==")
    fail_msg: "This playbook is intended for Ubuntu 20.04 only."

- name: Install required packages
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificates
      - gnupg
      - lsb-release
    state: present
    update_cache: true
  become: true

- name: Setup Vector repository
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL https://setup.vector.dev | bash
  args:
    executable: /bin/bash
    creates: /etc/apt/sources.list.d/vector.list
  become: true
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Install vector
  ansible.builtin.command:
      cmd: sudo apt-get install vector


- name: Render Vector config
  ansible.builtin.template:
    src: vector.yaml.j2
    dest: "{{ vector_config_path }}"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Validate Vector config
    - Restart Vector