---
- name: Validate Vector config
  ansible.builtin.command:
    cmd: "vector validate {{ vector_config_path }}"
  when: vector_validate_config | bool
  changed_when: false

- name: Restart Vector
  ansible.builtin.service:
    name: "{{ vector_service_name }}"
    state: restarted